name: Build and publish

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Build
        run: |
          npm install
          npm run build
      - name: Add & Commit
        uses: EndBug/add-and-commit@v8.0.2
        with:
          add: bundle.js --force
          commit: --signoff
